### ISSUE TITLE
Incompatible with Spring Boot 2.4

### ISSUE THREAD

**Issue by SirSkaro** [dlfigueira/spring-pokeapi#1]
`Hoxton` is not compatible with Spring Boot 2.4. However, `2020.0.0` is. 

The upgrade would require another dependency as well:

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bootstrap</artifactId>
</dependency>
```

Though this can can be worked around in the client's pom via `<dependencyManagement>` and adding the above dependency, I thought I'd bring it to your attention.

**Comment by dlfigueira** [comment]
Thank you for the report! I added GitHub's Dependabot in order to detect this issue in the future.
Please update to the new version (1.1.1) to fix this.
